### ISSUE TITLE
Old version of dependencies

### ISSUE THREAD

**Issue by dmytrovskyi** [Mindinventory/vimeo_video_player#34]
Hello!

Please update to the latest version of the dependencies.

```
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flick_video_player: ^0.7.0
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ```
